config/routes.rb
RailsShortener::Application.routes.draw do
  root 'welcome#index'

  resources :users do
    resources :urls
  end

  # resources :urls


  get ':short_url', to: 'urls#short_url'

  # CODE REVIEW: a common pattern here is to use a SessionsController for
  # signin/signout
  # http://ruby.railstutorial.org/chapters/sign-in-sign-out#top
  get 'logout/users', to: 'users#logout'

  post 'login/users', to: 'users#login'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/url.rb
class Url < ActiveRecord::Base
  belongs_to :user
  before_create :shorten_url
  validate :validate_url

  def shorten_url
    # CODE REVIEW: not protected against non-unique URLs
    self.shortened_url = rand(99).to_s.concat(('a'..'z').to_a.sample).concat(('a'..'z').to_a.sample).concat(rand(99).to_s).concat(('a'..'z').to_a.sample)
  end

  # CODE REVIEW: this is better done as a helper. Then you can take advantage of
  # Rail's URL generation helpers
  def to_url
    "http://oursite.#{shortened_url}"
  end

  def listify
    "#{to_url}   (#{url}) - Clicks: #{self.click_count}"
  end

  # CODE REVIEW: for every errors.add here, I'd probably have a seperate 
  # validate method
  def validate_url
    if self.url == "" || ! self.url.match(/.+\.\w{2,}/)
      return errors.add(:url, "This is not a valid web address!")
    end
    unless self.url.match(/\Ahttps?:\/\//)
      self.url = "http://".concat(self.url)
    end
    begin
      parsed_uri = URI(self.url)
      rescue
      return errors.add(:url, "This is not a valid web address!")
    end
    response = Net::HTTP.get_response(parsed_uri)
    unless 200 <= response.code.to_i && response.code.to_i < 400 && response.code.to_i != 303
      return errors.add(:url, "This is not a valid web address!")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :urls

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def short_url
    # CODE REVIEW: I would have used:
    # Url.where(:shortened_url => params[:short_url]).first
    @url = Url.where('shortened_url =?', params[:short_url])[0]
    # CODE REVIEW: see AR's #increment
    @url.click_count += 1
    @url.save
    redirect_to(@url.url)
  end

  def create
    # raise params.inspect
    @url = Url.new(url_params)
    if @url.save
      flash[:notice] = "You did it, dude!  Your shortened url is #{@url.shortened_url}"
    else
      flash[:notice] = "Naw, dude, naw.  You have to put in a real website, okay?"
    end
    redirect_to '/'
  end

  private

  def url_params
    x = params.require(:url).permit(:url)
    # CODE REVIEW: see Hash#merge
    x[:user_id] = params[:user_id]
    x
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You did it, dude!  Your account frakking exists"
      session[:user_id] = @user.id
    else
      flash[:notice] = "Naw, dude, naw.  You failed and are clearly a cylon"
    end
    redirect_to('/')
  end

  def logout
    redirect_to("/")
    session[:user_id] = nil
  end

  def login
    @user = User.where(username: params[:username]).first
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
    else
      flash[:notice] = "Wrong login info"
    end
    redirect_to '/'
  end

  private

  def user_params
    params[:user].permit(:username, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @urls = Url.order(click_count: :desc)
    @url = Url.new
    # CODE REVIEW: begging for a current_user helper
    @user = User.where(id: session[:user_id]).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsShortener</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
This is where we make new users
<%= form_for @user do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
</div>
    <%= f.submit %>

<% end %>

app/views/welcome/_logged_in_view.html.erb
<%= link_to("logout", logout_users_path) %>
<%= form_for [@user, @url] do |f|%>

  <%= f.label :url %>
  <%= f.text_field :url, autofocus: true %>
  <%= f.submit %>
<% end %>

<h3>Your shortened URLs:</h3>
  <% @user.urls.each do |url| %>
    <a href=<%="/#{url.shortened_url}"%>><%= url.listify %></a>
    <br>
  <% end %>

app/views/welcome/_not_logged_in_view.html.erb
    <h1>WHY YOU NO LOG IN????</h1>
    <h2>WE DO ALL THIS WORK AND YOU DON'T LOG IN? DISHONOR ON YOUR COW!</h2>

    <%= link_to 'Make an account', new_user_path %>

    <%= form_tag(action: 'login', method: 'post', controller: "users") do %>
      <%= label_tag :username %>
      <%= text_field_tag :username %>
      <%= label_tag :password %>
      <%= password_field_tag :password%>
      <%= submit_tag "Log In" %>
    <% end %>

app/views/welcome/_show_urls.html.erb
<h3>All URLs in their shortened glory:</h3>

<% @urls.each do |url| %>
  <a href=<%="/#{url.shortened_url}"%>><%= url.listify %></a>
  <br>
<% end %>

app/views/welcome/_welcome_message.html.erb
<% if @user %>
  <h1>Welcome to Your Dreams, <%= @user.username %>!</h1>
<% else %>
  <h1>Welcome to Your Dreams!</h1>
<% end %>

<h3>We'll shorten all of your (valid) URLs, just like Mom used to.</h3>
<p>Go ahead, give us something to shorten!</p>

<% if flash[:notice]%>
  <h2><%= flash[:notice]%></h2>
<% end %>

app/views/welcome/index.html.erb
<div class="container">
  <%= render "welcome_message" %>
  <% if @user %>
    <%= render "logged_in_view" %>
  <% else%>
    <%= render "not_logged_in_view" %>
  <% end %>
    <%= render "show_urls" %>
</div>